### ISSUE TITLE
NOTE TO DEVELOPER

### ISSUE THREAD

**Issue by AdamSchmidty** [davidteather/python-obfuscator#22]
Ok so.
You don't have any arguments. You just keep talking about my "ego" and "it's sad". But I'm just pointing out the
truth.
Beginners and skids (like you I suppose) think this obfuscation is good... but this cause lots of errors because of
the use of regex... and also the code is just surrounded by random variables who make the file really heavy and
easy to deobfuscate. So yes it is really really bad.
My obfuscator, Hyperion, is 1000x better than this one. The obfuscation is 1000x more complex and well-protected.

**Comment by davidteather** [comment]
💯
