### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by ianre657** [davidteather/python-obfuscator#3]
Perhaps it's a mistake, I found out that you pointed your [python-obfuscator][obf] on PyPI to [davidteather/TikTok-Api][tk] instead of this repo.

[obf]: https://pypi.org/project/python-obfuscator/
[tk]:https://github.com/davidteather/TikTok-Api

**Comment by davidteather** [comment]
You're right I forgot to release an update to pypi with the url. Thanks for reminding me
